name: WebARKitLib test

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Build and test WebARKitLib
          run: |
              cd tests && mkdir build && cd build && cmake -DEMSCRIPTEN_COMP=0 .. && make && ./webarkit_test
        - name: Build WebARKitLib with Emscripten (Docker)
          run: docker run -dit --name emscripten-webarkit-testing -v $(pwd):/src emscripten/emsdk:3.1.26 bash
        - run: docker exec emscripten-webarkit-testing emcmake cmake -B emscripten/WebARKitLib/WebARKit/build -Semscripten/WebARKitLib/WebARKit -DEMSCRIPTEN_COMP=1 ..
        - run: docker exec emscripten-webarkit-testing emmake make -C emscripten/WebARKitLib/WebARKit/build
              